defaults: &defaults
  docker:
    - image: sloanahrens/devops-toolkit-ci-dev-env:0.1

version: 2
jobs:

  python_linting:
    <<: *defaults
    steps:
      - checkout
      # - run:
      #     name: "Pip Install"
      #     command: pip install flake8>=3.7.7 --user circleci
      # - run:
      #     name: "Python Linting"
      #     command: cd django/stockpicker && python -m flake8 --ignore E501

  image_build_test_push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.2'
      - run:
          name: Build Images
          command: |
            set -x
            IMAGE_TAG=$(echo "$CIRCLE_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g'| sed -e 's/\(.*\)/\L\1/')
            bash bash-scripts/images/build-docker-images.sh
      - run:
          name: Docker-Compose Tests
          command: |
            set -x
            IMAGE_TAG=$(echo "$CIRCLE_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g'| sed -e 's/\(.*\)/\L\1/')
            bash bash-scripts/testing/docker-compose-stack-test-local.sh
      - run:
          name: Push to ECR
          command: |
            set -x
            IMAGE_TAG=$(echo "$CIRCLE_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g'| sed -e 's/\(.*\)/\L\1/')
            docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/src \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e IMAGE_TAG \
            devops \
            bash /src/bash-scripts/images/push-docker-images.sh
      - run:
          name: K8s Tests
          command: |
            set -x
            IMAGE_TAG=$(echo "$CIRCLE_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g'| sed -e 's/\(.*\)/\L\1/')
            echo "-- Attempting to pull kubeconfig..."
            docker run \
              -v $PWD:/src \
              -e AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY \
              -e SOURCE_PATH \
              devops bash /src/bash-scripts/k8s-clusters/pull-kube-config.sh

  prod_stack_deployment:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.2'
      # - run:
      #     name: Build Stack Tester Image
      #     command: |
      #       set -x
      #       docker build -t stacktest -f docker/stacktest/Dockerfile .
      - run:
          name: Build and Test Production K8s Stack
          command: |
            set -x
            IMAGE_TAG=$(echo "$CIRCLE_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g'| sed -e 's/\(.*\)/\L\1/')
            echo "-- Attempting to pull kubeconfig..."
            docker run \
              -v $PWD:/src \
              -e AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY \
              -e SOURCE_PATH \
              devops bash /src/bash-scripts/k8s-clusters/pull-kube-config.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - python_linting
      - image_build_test_push:
          requires:
            - python_linting
      - prod_stack_deployment:
          requires:
            - image_build_test_push
          # filters:
          #   branches:
          #     only:
          #       - master