defaults: &defaults
  docker:
    - image: sloanahrens/devops-toolkit-ci-dev-env:0.3

version: 2
jobs:

  python_linting:
    <<: *defaults
    steps:
      - checkout
      # - run:
      #     name: "Pip Install"
      #     command: pip install flake8>=3.7.7 --user circleci
      # - run:
      #     name: "Python Linting"
      #     command: cd django/stellarbot && python -m flake8 --ignore E501

  javascript_linting:
    <<: *defaults
    steps:
      - checkout

  image_build_test_push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.2'
      - run:
          name: Build Images
          command: |
            set -x
            export IMAGE_TAG=$(python3 -c "import re; print(re.sub('[^0-9a-zA-Z]+', '-', '${CIRCLE_BRANCH}').lower())")
            echo "IMAGE_TAG: ${IMAGE_TAG}"
            bash bash-scripts/images/build-docker-images.sh
      - run:
          name: Docker-Compose Tests Local
          command: |
            set -x
            export IMAGE_TAG=$(python3 -c "import re; print(re.sub('[^0-9a-zA-Z]+', '-', '${CIRCLE_BRANCH}').lower())")
            echo "IMAGE_TAG: ${IMAGE_TAG}"
            bash bash-scripts/testing/test-local-image-docker-compose-stack.sh
      - run:
          name: Push to ECR
          command: |
            set -x
            export IMAGE_TAG=$(python3 -c "import re; print(re.sub('[^0-9a-zA-Z]+', '-', '${CIRCLE_BRANCH}').lower())")
            echo "IMAGE_TAG: ${IMAGE_TAG}"
            source docker/repo.sh
            $(aws ecr get-login --no-include-email --region ${ECR_REGION})
            docker tag ui ${ECR_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${PROJECT_NAME}/ui:${IMAGE_TAG}
            docker tag django ${ECR_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${PROJECT_NAME}/django:${IMAGE_TAG}
            docker tag api-gateway ${ECR_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${PROJECT_NAME}/api-gateway:${IMAGE_TAG}
            docker push ${ECR_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${PROJECT_NAME}/ui:${IMAGE_TAG}
            docker push ${ECR_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${PROJECT_NAME}/django:${IMAGE_TAG}
            docker push ${ECR_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${PROJECT_NAME}/api-gateway:${IMAGE_TAG}
      - run:
          name: Docker-Compose Tests Tagged
          command: |
            set -x
            export IMAGE_TAG=$(python3 -c "import re; print(re.sub('[^0-9a-zA-Z]+', '-', '${CIRCLE_BRANCH}').lower())")
            echo "IMAGE_TAG: ${IMAGE_TAG}"
            source docker/repo.sh
            export ROOT_PATH=.
            docker system prune -af --volumes
            docker build -t stacktest -f docker/stacktest/Dockerfile .
            bash bash-scripts/testing/test-tagged-image-docker-compose-stack.sh

  validate_k8s_cluster:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Validate Kubernetes Cluster
          command: |
            set -x
            export SOURCE_PATH="kubernetes/us-east-2/dev"
            source ${SOURCE_PATH}/environment.sh
            export ROOT_PATH=.
            bash bash-scripts/k8s-clusters/pull-kube-config.sh
            if [ -f "${SOURCE_PATH}/cluster/kubecfg.yaml" ]; then
              bash bash-scripts/k8s-clusters/validate-cluster.sh
            else
              echo "-- Kubernetes cluster not found."
              exit 1
            fi

  k8s_stack_tests:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.2'
      - run:
          name: Build Stack Tester Image
          command: |
            set -x
            docker build -t stacktest -f docker/stacktest/Dockerfile .
      - run:
          name: Build and Test K8s Stack
          command: |
            set -x
            export IMAGE_TAG=$(python3 -c "import re; print(re.sub('[^0-9a-zA-Z]+', '-', '${CIRCLE_BRANCH}').lower())")
            export SOURCE_PATH="kubernetes/us-east-2/dev"
            export ROOT_PATH=.
            source ${SOURCE_PATH}/environment.sh
            export STACK_NAME="ci-${CIRCLE_BUILD_NUM}-${IMAGE_TAG}"
            echo "SOURCE_PATH: ${SOURCE_PATH}"
            echo "IMAGE_TAG: ${IMAGE_TAG}"
            echo "STACK_NAME: ${STACK_NAME}"
            echo "-- Attempting to pull kubeconfig..."
            bash bash-scripts/k8s-clusters/pull-kube-config.sh
            echo "-- Deploying K8s app-stack to ${CLUSTER_REGION}..."
            bash bash-scripts/app-stacks/deploy-k8s-app-stack.sh
            # this is inelegant, but avoids DNS cacheing problems in test script
            echo "-- Sleeping 120 seconds..."
            sleep 120
            echo "-- Running API integration-tests against K8s app-stack..."
            bash bash-scripts/testing/test-kubernetes-stack.sh
            echo "-- Destroying app-stack..."
            bash bash-scripts/app-stacks/destroy-k8s-app-stack.sh
            echo "-- Kubernetes-stack integration tests succeeded."

  prod_k8s_stack_deployment:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.2'
      - run:
          name: Build Stack Tester Image
          command: |
            set -x
            docker build -t stacktest -f docker/stacktest/Dockerfile .
      - run:
          name: Build and Test Production K8s Stack
          command: |
            set -x
            export IMAGE_TAG=master
            export STACK_NAME=stellarbot
            export SOURCE_PATH="kubernetes/us-east-2/dev"
            export ROOT_PATH=.
            echo "SOURCE_PATH: ${SOURCE_PATH}"
            echo "IMAGE_TAG: ${IMAGE_TAG}"
            echo "STACK_NAME: ${STACK_NAME}"
            echo "-- Attempting to pull kubeconfig..."
            source ${SOURCE_PATH}/environment.sh
            bash bash-scripts/k8s-clusters/pull-kube-config.sh
            echo "-- Deploying K8s app-stack to ${CLUSTER_REGION}..."
            bash bash-scripts/app-stacks/deploy-k8s-app-stack.sh
            echo "-- Sleeping 120 seconds..."
            sleep 120
            echo "-- Running API integration-tests against '${IMAGE_TAG}' app-stack..."
            bash bash-scripts/testing/test-kubernetes-stack.sh
            echo "-- Kubernetes-stack integration tests succeeded."

  # legacy_stack_deployment:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: '20.10.2'
  #     - run:
  #         name: Build and Test Production EC2/Docker-Compose Stack
  #         command: |
  #           set -x
  #           export REGION=us-east-1
  #           export DEPLOYMENT_TYPE=production
  #           export R53_ZONE=Z1CDZE44WDSMXZ
  #           export AWS_KEY_NAME=devops-toolkit-key
  #           export ROOT_PATH=/root/project
  #           docker build -t stacktest -f docker/stacktest/Dockerfile .
  #           bash bash-scripts/legacy-aws/deploy-docker-compose-ec2-rds-stack.sh
  #           sleep 180
  #           docker run -e SERVICE='https://master.stellarbotdev.com/api/v0.1' -e TESTERUSER_PASSWORD stacktest ./integration-tests.sh


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - python_linting
      - javascript_linting
      - validate_k8s_cluster
      - image_build_test_push
      - k8s_stack_tests:
          requires:
            - image_build_test_push
            - validate_k8s_cluster
      - prod_k8s_stack_deployment:
          requires:
            - k8s_stack_tests
          filters:
            branches:
              only:
                - master
