FROM baseimage

ENV C_FORCE_ROOT true

WORKDIR /src

COPY ./django/stockpicker/stockpicker /src/stockpicker
COPY ./django/stockpicker/tickers /src/tickers
COPY ./django/stockpicker/manage.py /src/manage.py