# Generated by Django 2.2.3 on 2019-07-12 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('adj_close', models.FloatField(default=0)),
                ('index_adj_close', models.FloatField(default=0)),
                ('scaled_adj_close', models.FloatField(default=0)),
                ('sac_moving_average', models.FloatField(default=0)),
                ('sac_to_sacma_ratio', models.FloatField(default=0)),
                ('quotes_in_moving_average', models.IntegerField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickers.Ticker')),
            ],
        ),
    ]
