# Generated by Django 3.1.4 on 2022-01-27 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('raw_json', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLogLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('boilerplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stellarbot.boilerplate')),
                ('asset_code', models.TextField()),
                ('asset_issuer', models.TextField()),
                ('asset_type', models.TextField()),
                ('amount', models.FloatField(default=0.0)),
                ('num_accounts', models.IntegerField(default=0)),
                ('trade_count', models.IntegerField(default=0)),
                ('volume', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('whitelisted', models.BooleanField(default=False)),
            ],
            bases=('stellarbot.boilerplate',),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('boilerplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stellarbot.boilerplate')),
            ],
            bases=('stellarbot.boilerplate',),
        ),
        migrations.CreateModel(
            name='AssetTuple',
            fields=[
                ('boilerplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stellarbot.boilerplate')),
                ('description', models.TextField(default='')),
                ('left_buy_amount', models.FloatField(default=0.0)),
                ('right_spend_amount', models.FloatField(default=0.0)),
                ('price_diff', models.FloatField(default=0.0)),
                ('rel_error', models.FloatField(default=0.0)),
                ('diff_in_xlm', models.FloatField(default=0.0)),
                ('left_tx_string', models.TextField(default='{}')),
                ('right_tx_string', models.TextField(default='{}')),
                ('asset_set', models.ManyToManyField(to='stellarbot.Asset')),
                ('bridge_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_asset_set', to='stellarbot.asset')),
            ],
            bases=('stellarbot.boilerplate',),
        ),
        migrations.CreateModel(
            name='Accumlation',
            fields=[
                ('boilerplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stellarbot.boilerplate')),
                ('amount', models.FloatField(default=0.0)),
                ('amount_in_xlm', models.FloatField(default=0.0)),
                ('asset_tuple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellarbot.assettuple')),
            ],
            bases=('stellarbot.boilerplate',),
        ),
    ]
